// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjCursoAPIDotNetCoreMVC.Data;

namespace ProjCursoAPIDotNetCoreMVC.Migrations
{
    [DbContext(typeof(ProjCursoAPIDotNetCoreMVCContext))]
    [Migration("20210923214514_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursoWebCoreMVC.Models.Enfermeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoInternoEnfermeiro")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Enfermeiro");
                });

            modelBuilder.Entity("CursoWebCoreMVC.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("CursoWebCoreMVC.Models.MaterialConsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EnfermeiroId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtdProduto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnfermeiroId");

                    b.ToTable("MaterialConsumo");
                });

            modelBuilder.Entity("CursoWebCoreMVC.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dosagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnfermeiroId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadeDosagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EnfermeiroId");

                    b.ToTable("Medicamento");
                });

            modelBuilder.Entity("CursoWebCoreMVC.Models.MaterialConsumo", b =>
                {
                    b.HasOne("CursoWebCoreMVC.Models.Enfermeiro", "Enfermeiro")
                        .WithMany()
                        .HasForeignKey("EnfermeiroId");

                    b.Navigation("Enfermeiro");
                });

            modelBuilder.Entity("CursoWebCoreMVC.Models.Medicamento", b =>
                {
                    b.HasOne("CursoWebCoreMVC.Models.Enfermeiro", "Enfermeiro")
                        .WithMany()
                        .HasForeignKey("EnfermeiroId");

                    b.Navigation("Enfermeiro");
                });
#pragma warning restore 612, 618
        }
    }
}
